services:
  db:
    image: postgres:17-alpine
    volumes:
      - ./var/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kandangdata

  redis:
    image: redis:7.4-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass your_password_here --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
