"""increase performance by removing uniquecontrait

Revision ID: 276d5b3cb07f
Revises: 770ed4d3da5e
Create Date: 2026-05-27 09:59:39.546098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276d5b3cb07f'
down_revision: Union[str, Sequence[str], None] = '770ed4d3da5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_node_name_per_parent'), 'nodes', type_='unique')
    op.create_index('uq_node_name_per_parent', 'nodes', ['parent_id', 'name', 'owner_id'], unique=True, postgresql_where='deleted_at is NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_node_name_per_parent', table_name='nodes', postgresql_where='deleted_at is NULL')
    op.create_unique_constraint(op.f('uq_node_name_per_parent'), 'nodes', ['parent_id', 'name', 'owner_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
