"""add vector_search field to node table

Revision ID: 46ae97f6a68a
Revises: 082889ccb4eb
Create Date: 2026-05-14 17:20:14.705160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46ae97f6a68a'
down_revision: Union[str, Sequence[str], None] = '082889ccb4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(name, ''))", ), nullable=True))
    op.create_index('idx_nodes_search_vector', 'nodes', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nodes_search_vector', table_name='nodes', postgresql_using='gin')
    op.drop_column('nodes', 'search_vector')
    # ### end Alembic commands ###
