"""create starred node table

Revision ID: 770ed4d3da5e
Revises: f9938dfac765
Create Date: 2026-05-18 07:46:57.918673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770ed4d3da5e'
down_revision: Union[str, Sequence[str], None] = 'f9938dfac765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starred_nodes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    op.create_index('idx_starred_node_id', 'starred_nodes', ['node_id'], unique=False)
    op.create_index('idx_starred_user_id', 'starred_nodes', ['user_id'], unique=False)
    op.drop_index(op.f('idx_nodes_name_trgm'), table_name='nodes', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_nodes_name_trgm'), 'nodes', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_starred_user_id', table_name='starred_nodes')
    op.drop_index('idx_starred_node_id', table_name='starred_nodes')
    op.drop_table('starred_nodes')
    # ### end Alembic commands ###
