"""add preview_url in node table

Revision ID: 88af978a3489
Revises: fd8efdb90122
Create Date: 2026-05-13 07:37:19.372586

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88af978a3489"
down_revision: Union[str, Sequence[str], None] = "fd8efdb90122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("preview_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "preview_url")
    # ### end Alembic commands ###
