"""create upload sessions table

Revision ID: fd8efdb90122
Revises: 3d9dbddd348f
Create Date: 2026-05-01 11:38:11.677154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8efdb90122'
down_revision: Union[str, Sequence[str], None] = '3d9dbddd348f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=False),
    sa.Column('chunk_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'UPLOADING', 'COMPLETED', 'FAILED', name='uploadstatus'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
